version: "3.8"
services:
  nginx_test:
    container_name: nginx_test
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php_test
    ports:
      - "80:80"
    depends_on:
      - php_test
      - mysql_test
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./app:/var/www/html
    networks:
      - laravel_test
  php_test:
    container_name: php_test
    build: ./docker/php
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal start_with_request=yes
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql_test
    networks:
      - laravel_test
  mysql_test:
    hostname: mysql
    image: mysql:8.0.19
    container_name: mysql_test
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test_app
      MYSQL_USER: user_test
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_test
    networks:
      - laravel_test
  mailhog:
    container_name: mailhog_test
    image: 'mailhog/mailhog:latest'
    ports:
        - 1026:1025
        - 8026:8025
    networks:
        - laravel_test
networks:
  laravel_test:
    driver: bridge